apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 
  namespace: 
spec:
  secretName: 
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: 
    kind: ClusterIssuer
  dnsNames:
    - "*.example.com"
    - "example.com"

