apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: 
  namespace: metallb-system
spec:
  ipAddressPools:
    - IPAddressPool_NAME
  interfaces:
  - YOUR_INTERFACES
  nodeSelectors:
  - matchLabels:
      metallb.io/node: ENTRANCE_NODE

