apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertie
  namespace: metallb
spec:
  ipAddressPools:
    - metallb-ip
  interfaces:
  - YOUR_INTERFACES
  nodeSelectors:
  - matchLabels:
      metallb.io/node: ENTRANCE_NODE

