######Cloud service provider of choice######

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns01
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: YOUR_EMAIL 
    privateKeySecretRef:
      name: private-dns01
    solvers:
      - dns01:
         cloudflare:
           email: CLOUDFLARE_EMAIL
           apiTokenSecretRef:
             name: cloudflare-api-token
             key: api-token

